server:
  port: 10001
spring:
  application:
    name: service-one
  profiles:
    active: @environment@
  cloud:
    nacos:
      discovery:
        server-addr: @server-addr@
        service: service-one
        group: dev
  sleuth:
    sampler:
      # 日志数据采样百分比，默认0.1(10%)，这里为了测试设置成了100%，生产环境只需要0.1即可
      probability: 1.0
  zipkin:
    # zipkin server的请求地址
    base-url: http://127.0.0.1:9411
    # 让nacos把它当成一个URL，而不要当做服务名
    discovery-client-enabled: false
mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml