server:
  port: 10001
spring:
  application:
    name: service-one
  profiles:
    active: @environment@
  cloud:
    nacos:
      discovery:
        server-addr: @server-addr@
        service: service-one
        group: dev
mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug