management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/service_one?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    hikari:
      maximum-pool-size: 100
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1
swagger:
  enable: true
#dubbo:
#  application:
#    name: ${spring.application.name}
#  protocol:
#    port: 20881
#    name: dubbo
#  registry:
#    address: zookeeper://127.0.0.1:2181
#  provider:
#    version: 1.0
#    timeout: 8000
#    protocol: dubbo
#    threadname: dubbo
grpc:
  client:
    grpc-server:
      address: 'static://127.0.0.1:50051'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext