server:
  port: 10001
spring:
  application:
    name: service-one
  profiles:
    active: @environment@
  cloud:
    nacos:
      discovery:
        server-addr: @server-addr@
        service: service-one
        group: dev