server:
  port: 80
management:
  endpoint:
    gateway:
      enabled: true   #打开gateway的actuator端点
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: service-gateway
  profiles:
    active: @environment@
  cloud:
    nacos:
      discovery:
        server-addr: @server-addr@
        service: service-gateway
        group: dev
    gateway:
      discovery:
        locator:
          enabled: true #动态路由
          lower-case-service-id: true #使用小写服务名，默认是大写
      routes:
        - id: service-one
          uri: lb://service-one
          predicates:
            - Path=/api-service-one/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1   # 令牌桶每秒填充速率
                redis-rate-limiter.burstCapacity: 2   # 令牌桶总容量
                key-resolver: '#{@remoteAddrKeyResolver}'   # 使用 SpEL 表达式按名称引用 bean
        - id: service-two
          uri: lb://service-two
          predicates:
            - Path=/api-service-two/**
          filters:
            - StripPrefix=1
        - id: oauth
          uri: lb://oauth-server
          predicates:
            - Path=/oauth/**
          filters:
            - StripPrefix=1
