server:
  port: 10003
spring:
  application:
    name: admin
  profiles:
    active: @environment@
  cloud:
    nacos:
      discovery:
        server-addr: @server-addr@
        service: admin
        group: dev